services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    depends_on:
      - db
    networks:
      - appnet
  db:
    image: postgres:13.5-alpine
    restart: always
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_MANAGER: "fsm-postgres"
    networks:
      - appnet
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  appnet:

volumes:
  db-data: